# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-07 08:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 1, 7, 8, 24, 33, 446791, tzinfo=utc), verbose_name='Interview Date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interview',
            name='end_time',
            field=models.TimeField(verbose_name='Interview end time'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='start_time',
            field=models.TimeField(verbose_name='Interview start time'),
        ),
    ]
