# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-17 07:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20180107_0824'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_email', models.EmailField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User_Interview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='interview',
            name='candidate_email',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='interviewer_email',
        ),
        migrations.AddField(
            model_name='user_interview',
            name='interview_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Interview'),
        ),
        migrations.AddField(
            model_name='user_interview',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.User'),
        ),
    ]
